# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(default='will-be-generated-once-save'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='slug',
            field=models.SlugField(default='will-be-generated-once-save'),
        ),
        migrations.AlterField(
            model_name='restaurantcategory',
            name='slug',
            field=models.SlugField(default='will-be-generated-once-save'),
        ),
    ]
