# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0002_auto_20170330_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bm', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='ingredient_thumbnail')),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='will-be-generated-once-save')),
            ],
        ),
    ]
