# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0003_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bm', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('youtube_url', models.URLField()),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='recipe_thumbnail')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(default='will-be-generated-once-save')),
                ('ingredients', models.ManyToManyField(to='limau.Ingredient')),
                ('recipecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limau.RecipeCategory')),
            ],
        ),
    ]
