# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0004_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bm', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='article_thumbnail')),
                ('text_bm', models.TextField()),
                ('slug', models.SlugField(default='will-be-generated-once-save')),
                ('articlecategory', models.ManyToManyField(to='limau.ArticleCategory')),
            ],
        ),
    ]
