# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0005_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bm', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('building_thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='restaurant_thumbnail/building')),
                ('menu_thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='restaurant_thumbnail/menu')),
                ('food_thumbnail_1', imagekit.models.fields.ProcessedImageField(upload_to='restaurant_thumbnail/food')),
                ('food_thumbnail_2', imagekit.models.fields.ProcessedImageField(upload_to='restaurant_thumbnail/food')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('food_quality', models.IntegerField(choices=[[1, 'ONE'], [2, 'TWO'], [3, 'THREE'], [4, 'FOUR'], [5, 'FIVE']], default=1)),
                ('food_variety', models.IntegerField(choices=[[1, 'ONE'], [2, 'TWO'], [3, 'THREE'], [4, 'FOUR'], [5, 'FIVE']], default=1)),
                ('etiquette', models.IntegerField(choices=[[1, 'ONE'], [2, 'TWO'], [3, 'THREE'], [4, 'FOUR'], [5, 'FIVE']], default=1)),
                ('cleanliness', models.IntegerField(choices=[[1, 'ONE'], [2, 'TWO'], [3, 'THREE'], [4, 'FOUR'], [5, 'FIVE']], default=1)),
                ('access', models.IntegerField(choices=[[1, 'ONE'], [2, 'TWO'], [3, 'THREE'], [4, 'FOUR'], [5, 'FIVE']], default=1)),
                ('limau_meter', models.IntegerField(default=1)),
                ('slug', models.SlugField(default='will-be-generated-once-save')),
                ('restaurantcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limau.RestaurantCategory')),
            ],
        ),
    ]
