# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0007_auto_20170401_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='starhtml',
            field=models.TextField(default='nothing'),
        ),
    ]
