# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0011_userrecipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='name_en',
            field=models.CharField(max_length=128),
        ),
    ]
