# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-29 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0014_auto_20171012_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipe',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
