# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-30 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0015_userrecipe_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
