# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0016_auto_20171031_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='description', max_length=300),
        ),
    ]
