# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-26 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0019_auto_20171120_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='name_bm',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='name_en',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
