# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-27 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0020_auto_20171227_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='name_bm',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='name_en',
            field=models.CharField(max_length=128),
        ),
    ]
