# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0022_auto_20171227_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='description', max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='mobilebanner')),
            ],
        ),
    ]
