# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0023_mobilebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebanner',
            name='status',
            field=models.IntegerField(choices=[[1, 'ONE'], [2, 'TWO'], [3, 'THREE'], [4, 'FOUR'], [5, 'FIVE']], default=2),
        ),
    ]
