# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0024_mobilebanner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebanner',
            name='name',
            field=models.CharField(default='description', max_length=100),
        ),
    ]
