# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0025_auto_20180105_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebanner',
            name='status',
            field=models.IntegerField(choices=[[1, 'active'], [2, 'nonactive']], default=2),
        ),
    ]
