# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0027_mobilebanner_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilebanner',
            old_name='url',
            new_name='image_url',
        ),
    ]
