# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0028_auto_20180108_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badge',
            field=models.IntegerField(choices=[[1, 'gold'], [2, 'silver'], [3, 'bronze']], default=3),
        ),
    ]
