# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-19 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0030_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
