# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-21 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0031_announcement_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(default='fill in step by step instruction here'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serve',
            field=models.IntegerField(choices=[[1, 'ONE'], [2, 'TWO'], [3, 'THREE'], [4, 'FOUR'], [5, 'FIVE'], [6, 'SIX'], [6, 'SEVEN'], [6, 'EIGHT'], [6, 'NINE'], [6, 'TEN']], default=3),
        ),
    ]
