# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-28 02:46
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0033_auto_20180121_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail2',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='recipe_thumbnail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='thumbnail3',
            field=imagekit.models.fields.ProcessedImageField(default=datetime.datetime(2018, 1, 28, 2, 46, 55, 360160, tzinfo=utc), upload_to='recipe_thumbnail'),
            preserve_default=False,
        ),
    ]
