# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-28 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0034_auto_20180128_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecipe',
            name='content',
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='ingredients',
            field=models.TextField(default='key in your ingredienst here in <li>ingredients</li> tag'),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='instructions',
            field=models.TextField(default='key in your instruction here in <li>ingredients<li> tag'),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='description',
            field=models.TextField(default='my food is the best in the world!!', max_length=300),
        ),
    ]
