# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0035_auto_20180129_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='fill in your product name here', max_length=100)),
                ('image_1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products')),
                ('image_2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products')),
                ('image_3', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products')),
                ('image_4', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_switch', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default='5')),
                ('in_stock', models.BooleanField(default=True)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(default='will be generated once save')),
            ],
        ),
    ]
