# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-09 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0038_auto_20180209_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default='50.00', max_digits=10),
        ),
    ]
