# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0039_auto_20180209_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='definition',
            field=models.CharField(default='Fill in product short definition here', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='optional_definition',
            field=models.TextField(default='Fill in extra definition in HTML form here if switch = true'),
        ),
        migrations.AddField(
            model_name='product',
            name='optional_definition_switch',
            field=models.BooleanField(default=True),
        ),
    ]
