# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-11 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0041_auto_20180211_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='productBanners')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
