# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-12 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limau', '0043_auto_20180212_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default='will-be-generated-once-save'),
        ),
    ]
